music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands, only: [:new, :create, :destroy, :show, :update, :edit, :index] do 
    resources :albums, only: [:new]
  end 
  resources :albums, only: [:create, :destroy, :edit, :show, :update]
    
end
 
# new_band_album GET    /bands/:band_id/albums/new(.:format)   albums#new
#         albums POST   /albums(.:format)                      albums#create
#     edit_album GET    /albums/:id/edit(.:format)             albums#edit
#          album GET    /albums/:id(.:format)                  albums#show
#                PATCH  /albums/:id(.:format)                  albums#update
#                PUT    /albums/:id(.:format)                  albums#update
#                DELETE /albums/:id(.:format)                  albums#destroy

music_app/app/models/album.rb
class Album <ApplicationRecord 

  TYPES = %w(live studio)

  validates :title, presence: true 
  validates :band_id, presence: true 
  validates :recordings, inclusion: { in: TYPES }
  validates :year, presence: true

  belongs_to :band, 
    primary_key: :id, 
    foreign_key: :band_id, 
    class_name: :Band 

end 

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true, uniqueness: true 

    has_many :albums, 
    primary_key: :id, 
    foreign_key: :band_id, 
    class_name: :Album

end 

music_app/app/models/user.rb
class User < ApplicationRecord 
  
  validates :email, presence: true, uniqueness: true 
  validates :password_digest, presence: true
  validates :session_token, presence: true 
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user 
    else
      nil 
    end 
  end 

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end 

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end 

  def password=(password)
    @password = password 
    self.password_digest = BCrypt::Password.create(password)
    self.password_digest
  end 

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end 

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end 
end 

music_app/app/controllers/albums_controller.rb
class AlbumsController <ApplicationController

  def new 
    render :new 
  end 

  def create
    @album = Album.new(album_params)
    
    if @album.save
      flash[:errors] = ["#{@album.title} was added to the database"]
      redirect_to band_url(@album.band_id)
    else 
      flash.now[:errors] =[ "Album was not added to the database" ]
      render :new 
    end 
  end 
  
  def show 
    @album = Album.find(params[:id])
    if @album
      render :show 
    else 
      flash[:errors] = [ "This album was not found" ]
      redirect_to bands_url
    end 
  end 

  def edit 
    @album = Album.find(params[:id])
    if @album 
      render :edit 
    else 
      flash[:errors] = ["This album cannot be edited or does not exist"]
      redirect_to bands_url 
    end 
  end 

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      flash.now[:errors] = [ "#{@album.name} was updated"]
      render :show 
    else 
      flash.now[:errors] = [ "This album was not properly updated" ]
      render :edit 
    end  
  end 

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy 
      flash[:errors] = [ "The album was removed from the database" ]
      redirect_to band_url(params[:band_id])
    else 
      flash.now[:errors] = [ "This album could not be removed from the database" ]
      render :show 
    end 
  end 

  private 

  def album_params 
    params.require(:album).permit(:title, :band_id, :recordings, :year, :band_id) 
  end 

end 

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? 

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end 

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end 

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end 

  def logout!(user)
    #debugger
    current_user.reset_session_token! 
    session[:session_token] = nil 
    @current_user = nil 
  end 

  def logged_in?
    !!current_user
  end 

end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    # [:new, :create, :destroy, :show, :update, :edit, :index]

    def new
      render :new 
    end 

    def create
      # debugger
      @band = Band.new(band_params)
      if @band.save 
        # debugger
        # @band = Band.find_by(name: band_params[:name])
        redirect_to band_url(@band)
      else 
        flash.now[:errors] = [ @band.errors.full_messages ]
        render :new #new_band_url
      end 
    end 
    
    def destroy
      band = Band.find(params[:id])
      if band 
        name = band.name
        band.destroy 
        flash[:errors] = [ "#{name} was deleted from the database"]
        redirect_to bands_url
      else 
        flash.now[:errors] = [ "This band does not exist in this database"]
        render :index
      end 
    end 

    def show 
      # debugger
      @band = Band.find(params[:id])
      if @band 
        render :show
      else 
        flash.now[:errors] = [ "This band does not exist in this database"]
        render :index
      end 
    end 

    def update
      @band = Band.find(params[:id])
      if @band.update(band_params)
        flash[:errors] = [ "#{@band.name} was updated"]
        redirect_to band_url(@band)
      else 
        flash.now[:errors] = [ @band.errors.full_messages ]
        render :edit
      end 
    end 

    def edit
      @band = Band.find(params[:id])
      if @band 
        render :edit 
      else 
        render plain: "That band does not exist in this system"
      end 
    end 

    def index 
      @band = Band.all 
      render :index 
    end 

    private 

    def band_params
      params.require(:band).permit(:name)
    end 
end 

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def new
    render :new
  end 

  def create 
    #debugger
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    #debugger 
    if user 
      login!(user)
      redirect_to user_url(user)
    else 
      flash.now[:errors] = [ "that login information was incorrect" ]
      render :new 
    end 
  end 

  def destroy 
    #debugger
    logout!(@user)
    redirect_to new_session_url
  end 

end  

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController 

  def new
    render :new
  end 

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to user_url(user)
    else 
      flash.now[:errors] = [ user.errors.full_messages ]
      render :new
    end 
  end 

  def show 
    @user = User.find(params[:id])
    render :show
  end 


  private 

  def user_params
    params.require(:user).permit(:email, :password)
  end 

end 

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/albums/new.html.erb
<h1>Add an album:</h1>


<form action="<%= albums_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="title">Album Name</label><br>
    <input type="text" name="album[title]" id="title"><br>
  <label for="live">Live<input type="radio" name="album[recordings]" id="recordings" value="live" checked></label>
  <label for="live">Studio<input type="radio" name="album[recordings]" id="recordings" value="studio"></label><br>
  <label for="year">Album Year</label><br>
    <input type="integer" name="album[year]" id="year"><br>
    <input type="hidden" name="album[band_id]" id="band_id" value="<%= params[:band_id] %>">
  <br><input type="submit" value="SUBMIT">
</form>

music_app/app/views/bands/edit.html.erb
<h1>Edit this Band</h1>

<form action="<%= band_url %>" method="POST">
 <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="name"><%= @band.name %></label><br>
    <input type="text" name="band[name]" id="name"><br>
  <input type="submit" value="SUBMIT">
</form>

music_app/app/views/bands/index.html.erb
<h1>Bands:</h1>

<% @band.each do |band| %>
  <h3><%= band.name %></h3>
  <form action="<%= band_url(band) %>" method="GET">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Learn more"> 
  </form>
<% end  %>

music_app/app/views/bands/new.html.erb
<h1>Add a band:</h1>


<form action="<%= bands_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="name">Band Name</label><br>
    <input type="text" name="band[name]" id="name"><br>
  <input type="submit" value="SUBMIT">
</form>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<% @band.albums.each do |album| %>
  <h3><%= album.title %></h3>
<% end %>

<form action="<%= band_url %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Delete this band from database"> 
</form>

<form action="<%= edit_band_url %>" method="GET">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Edit this band"> 
</form>

<form action="<%= bands_url %>" method="GET">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="See all bands"> 
</form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header class="logio">Music App
<% if current_user %>
  <form class="log" action="<%= session_url %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Logout">
  </form>
<% else %>
  <form class="log" action="<%= new_session_url %>" method="GET">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Login">
  </form>
<% end %> 
</header>

  <body>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end  %>
    <% end  %>

    <%= yield %>
  </body>

  <footer>coyright: PS</footer>
  </div>
</html>

music_app/app/views/users/new.html.erb
<!-- New User page -->

<h1>Create a profile: </h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="email">Enter your email</label><br>
    <input type="text" name="user[email]" id="email"><br>
  <label for="password">Please enter a password</label><br>
    <input type="password" name="user[password]" id="password"><br>
  <input type="submit" value="SUBMIT">

</form>

music_app/app/views/users/show.html.erb
<!--User Homepage-->

<h1>This is, <%= @user.email %></h1>


<form action="<%= bands_url %>" method="GET">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="See all bands"> 
</form>